name: maven github actions
on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  tests:
    name: Run test for maven
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: running tests
        run: mvn test
  build:
    needs: tests
    name: Building maven
    runs-on: ubuntu-latest
    outputs:
      artifact-data: ${{ steps.artifact-name.outputs.artifact_name }}
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: building the jar
        run: mvn clean package
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: myjava-jar
          path: target/*.jar
      - name: display content of target
        run: ls -R target
      - name: Get the name of the output file
        id: artifact-name
        run: find target/*.jar -type f -execdir echo 'artifact_name={}' >> $GITHUB_OUTPUT ';'
  deploy:
    needs: build
    name: Download and display jar file
    runs-on: ubuntu-latest
    steps:
      - name: get artifacts from build job
        uses: actions/download-artifact@v8
        with:
          name: myjava-jar
          path: target
      - name: display jar file
        run: ls -R target
      - name: name of the jar file
        run: echo ${{ needs.build.outputs.artifact-data }}
      
